---
title: "Preprocessing of Safaiyan et al. Lifespan Microglia"
author: "James Choi"
date: "Last compiled:`r Sys.Date()`"
output: 
  html_document
editor_options:
  chunk_output_type: 
    console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE, fig.align='center', 
                      tidy.opts=list(width.cutoff=80), tidy=TRUE,
                      results='hold')
```

```{r}
if(!grepl('scripts', getwd())) {setwd('scripts')}
results_out <- '../results/GSE166548_Safaiyan/'
data_out <- '../data/GSE166548_Safaiyan/'
dir.create(path = data_out)
```


GEO Accession: GSE166548

Data was provided by the following:

Title: White matter aging drives microglial diversity

Citation: Safaiyan S, Besson-Girard S, Kaya T, Cantuti-Castelvetri L et al. White matter aging drives microglial diversity. Neuron 2021 Apr 7;109(7):1100-1117.e10. PMID: 33606969

[Link to paper](https://doi.org/10.1016/j.neuron.2021.01.027)


```{r download_decompress}
dlcheck <- download.file(
  url = 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE166548&format=file&file=GSE166548%5F10xaged%2Etsv%2Egz',
  destfile = paste0(data_out, 'GSE166548_10xaged.tsv.gz'),
  mode = 'wb' # the TAR file is a binary
)
if (dlcheck != 0) {
  stop('GSE166548 download unsuccessful')
} else {
  counts <- read.table(
    file = gzfile(paste0(data_out, 'GSE166548_10xaged.tsv.gz')),
    sep = '\t',
    row.names = 1
  )
  counts <- as.matrix(counts)
  counts <- Matrix::Matrix(data = counts, sparse = TRUE)
}
# sample metadata provided kindly by authors via email correspondence
sample_metadata <- read.table(
  file = paste0(data_out, '10X_WT_Aging_all_metadata.tsv'),
  sep = '\t',
  header = TRUE
)
```

```{r}
sample_metadata$Cell.ID <- gsub(pattern = '-', '.', x = sample_metadata$Cell.ID)
if (!all(colnames(counts) == sample_metadata$Cell.ID)) {
  stop('Order of cells is not identical')
}
tmp_barcode <- sapply(strsplit(sample_metadata$Cell.ID, '\\.'), `[`, 1)
tmp_append <- paste('GSE166548', sample_metadata$Batch, sep = '')
tmp_barcode <- paste(tmp_barcode, tmp_append, sep = '_')
sample_metadata$barcode <- tmp_barcode
colnames(counts) <- tmp_barcode
counts <- counts[, !duplicated(colnames(counts))]
sample_metadata <- sample_metadata[!duplicated(sample_metadata$barcode),]
```

Setup metadata including experimental details.

```{r metadata}
# Set up metadata and experimental details
metadata <- data.frame(
  'study' = 'Safaiyan2021',
  'sample_id' = sapply(strsplit(colnames(counts), '_'), `[`, 2),
  'tissue' = plyr::mapvalues(x = colnames(counts),
                             from = sample_metadata$barcode,
                             to = sample_metadata$Tissue,
                             warn_missing = FALSE),
  'injury_model' = 'Aging',
  'age' = 'P720'
)
metadata$injury <- paste(metadata$tissue, 'Ctrl', sep = '.')
rownames(metadata) <- colnames(counts)
```

Save

```{r save}
Safaiyan2021 <- list(counts = counts, metadata = metadata)
saveRDS(Safaiyan2021, file = paste0(data_out, 'Safaiyan2021.rds'))
```

```{r}
sessionInfo()
```